### PR TITLE
Added two methods for checkitems

### PR DESCRIPTION
**Pull request by rdorrigan**
The methods below set due dates and add members. The Trello API does not list either actions officially but does support it it in the UI and both worked in my production environment.
set_checklist_item_due()
set_checklist_item_member()

### CODE REVIEW

**Comment by xu2xulim** [comment]
Line 551 remainder = int(remainder) does not allow for string like “60.5”. Suggest remainder = int(float(remainder))

**Comment by rdorrigan** [comment]
Thank you! Updated.

**Comment by xu2xulim** [comment]
Based on my test, it seems that member and due dates will not be visible unless you are on business class. Do you have the same experience?

**Comment by rdorrigan** [comment]
I'm on a business class account for work, and am not experiencing that issue. I could note this in the comments.

**Comment by xu2xulim** [comment]
Add file via Upload👏🤞👍✅

**Comment by sarumont** [comment]
Happy to merge if you can resolve the conflicts!

**Comment by rdorrigan** [comment]
Conflicts resolved. I know I had an odd response with a 'checkbox' custom_field.field type. Which required the conflicting edits. I'll see if I can find some evidence and make another pull request later on.

**Comment by rdorrigan** [comment]
Reopening, I accidentally closed by trying to tidy up branch names.

**Comment by sarumont** [comment]
Thanks, @rdorrigan! Merged!

**Comment by xu2xulim** [comment]
@rdorrigan 
Got this when testing the delete_custom_field_option. 
```
trello.exceptions.ResourceUnavailable: {"error":"CUSTOM_FIELD_OPTION_NOT_FOUND","message":"Custom field option not found"} at https://api.trello.com/1/customFields/60d998eff903b078cdc2fc3c/options/60d998eff903b078cdc2fc3c (HTTP status: 404)
```
Both the _**definition ID and the option ID are the same**_? When I define my own def with
```
json_obj = client.fetch_json(
        'customFields/{0}/options/**{1}**'.format(custom_field_definition_id,option_id),
        http_method='DELETE',
```
See highlighted portion.

**Comment by rdorrigan** [comment]
@xu2xulim Thank you for identifying the error. I've tested and committed the requested changes. @sarumont would prefer a new pull request be opened?

**Pull request merged**
