### PR TITLE
Break up code into files and integrated pull request #78

### PR DESCRIPTION
**Pull request by nMustaki**

### CODE REVIEW

**Comment by sarumont** [comment]
Thanks for this - definitely a good change since the library has grown. I'll review this week and merge it after bumping the major version, as this is a major break in the API.

**Comment by nMustaki** [comment]
Great!
In the meantime,  I'll break the tests into their own files just to be
consistent with these changes.

**Comment by genericmoniker** [comment]
This seems like a good organizational change (as was mentioned) -- are there still plans to merge it?

**Comment by nMustaki** [comment]
Oups sorry! @sarumont, what do you  think?

**Comment by sarumont** [comment]
Yup - this is a good mod. I'll plan to merge soon (I'm finding time to contribute to `py-trello` again, but it's coming in small chunks ;) )

**Comment by nMustaki** [comment]
Do you want/need help ?


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Comment by sarumont** [comment]
I won't say no to it. :)

The current PR has conflicts, so that will be the biggest time sink. Any
help toward that end would be appreciated.

**Comment by nMustaki** [comment]
I wonder if redoing this PR from the current state of the repo wouldn't be
easier...
I'll do it soon anyway

**Comment by nMustaki** [comment]
@sarumont can you merge the others pull request, so their work is not lost? Then I'll do this pr from scratch

**Comment by sarumont** [comment]
Nathan,

Sounds good. I'll merge tomorrow sometime.

**Comment by sarumont** [comment]
All material PRs have been merged. The other two are mere hygiene, so feel free to fix up this PR without them.

**Comment by nMustaki** [comment]
Great! I'll do it tonight hopefully

**Comment by nMustaki** [comment]
The shiny new one is PR #104

**Pull request closed without merging**
